version: '3.9'

services:
  web:
    build: .
    ports:
      - '8000:8000' #使用時ポート変更すること
    volumes:
      - ./src:/var/www/html
  db:
    platform: linux/x86_64
    image: mysql:5.7
    ports:
      - '3306:3306'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: laravel_test_api
    volumes:
      - ./db:/var/lib/mysql